version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expo-react-native-web
    ports:
      - "8081:8081"  # Expo web default port
      - "19006:19006"  # Expo dev server (optional if using expo start)
    environment:
      - NODE_ENV=production
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    restart: unless-stopped
    command: ["npx", "expo", "start", "--web", "--host", "lan"]
    volumes:
      # Optional: for development hot reload (comment out for production)
      # - .:/app
      # - /app/node_modules
      - /dev/null:/app/.env.local
