version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: venusa-web-frontend
    ports:
      - "8080:80"  # Serve static site on external port 8080 since port 80 is in use
    restart: unless-stopped
