version: '3.8'

services:
  venusa-frontend:
    build: .
    container_name: venusa-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    restart: unless-stopped
    environment:
      - NGINX_HOST=venusa.co.in
      - NGINX_PORT=80
    networks:
      - venusa-network

networks:
  venusa-network:
    driver: bridge